### ISSUE TITLE
Render feature is broken in flatpak

### ISSUE THREAD

**Issue by whereswaldon** [flathub/org.pitivi.Pitivi#23]
Using this flatpak on Fedora 33, I am unable to render a project.

When I click the "Render" button, nothing happens. There is no popup window asking for export settings or anything.

I reran using `flatpak run org.pitivi.Pitivi`, and I see this in the log when I click the "Render" button:
```
Traceback (most recent call last):
  File "/app/lib/pitivi/python/pitivi/editorperspective.py", line 168, in _render_cb
    dialog = RenderDialog(self.app, project)
  File "/app/lib/pitivi/python/pitivi/render.py", line 836, in __init__
    self._display_settings()
  File "/app/lib/pitivi/python/pitivi/render.py", line 1094, in _display_settings
    assert res, self.project.audiorate
AssertionError: 32000
```

I'm running GNOME Wayland, and the `flatpak list` line for Pitivi looks like this:
```
Pitivi                                         org.pitivi.Pitivi                           2021.01         stable        system
```

I apologize if this is the wrong place to report such issues, but this problem seems likely to be in the packaging, so thought I'd try here. Happy to provide additional diagnostic information!

**Comment by whereswaldon** [comment]
Okay, thank you!
