### ISSUE TITLE
TypeError: constructor returned NULL from Gdk.Cursor.new(Gdk.CursorType.TCROSS)

### ISSUE THREAD

**Issue by PorcelainMouse** [flathub/org.pitivi.Pitivi#26]
Sorry, new to Piviti, but flatpak version crashes on start for me.

`$ flatpak run org.pitivi.Pitivi
Gdk-Message: 22:36:25.686: Unable to load tcross from the cursor theme
Traceback (most recent call last):
  File "/app/lib/python3.8/site-packages/matplotlib/backends/backend_gtk3.py", line 43, in <module>
    cursors.SELECT_REGION: Gdk.Cursor.new(Gdk.CursorType.TCROSS),
TypeError: constructor returned NULL

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/bin/pitivi", line 172, in <module>
    _run_pitivi()
  File "/app/bin/pitivi", line 143, in _run_pitivi
    from pitivi import application
  File "/app/lib/pitivi/python/pitivi/application.py", line 32, in <module>
    from pitivi.mainwindow import MainWindow
  File "/app/lib/pitivi/python/pitivi/mainwindow.py", line 29, in <module>
    from pitivi.editorperspective import EditorPerspective
  File "/app/lib/pitivi/python/pitivi/editorperspective.py", line 41, in <module>
    from pitivi.timeline.timeline import TimelineContainer
  File "/app/lib/pitivi/python/pitivi/timeline/timeline.py", line 37, in <module>
    from pitivi.timeline.elements import Clip
  File "/app/lib/pitivi/python/pitivi/timeline/elements.py", line 31, in <module>
    from matplotlib.backends.backend_gtk3cairo import FigureCanvasGTK3Cairo
  File "/app/lib/python3.8/site-packages/matplotlib/backends/backend_gtk3cairo.py", line 6, in <module>
    from . import backend_cairo, backend_gtk3
  File "/app/lib/python3.8/site-packages/matplotlib/backends/backend_gtk3.py", line 49, in <module>
    raise ImportError(exc) from exc
ImportError: constructor returned NULL
`

**Comment by Zlopez** [comment]
I can confirm this is happening to me as well on Fedora 35 Kinoite.

**Comment by aleb** [comment]
It might be due to an incomplete system theme. Can you try with the standard Adwaita?

**Comment by Zlopez** [comment]
I changed the theme to Adwaita, but still the same result.

**Comment by hfiguiere** [comment]
the other thing is that this is still running on a EOL runtime.

PR #24 is still waiting.

**Comment by snydox** [comment]
I'm running Fedora 36 and I can confirm I'm also dealing with this error.

**Comment by aleb** [comment]
This is https://gitlab.gnome.org/GNOME/pitivi/-/issues/2600 and has been fixed. We still need to do a release to distribute the fix. Some remaining issues to be fixed though. https://gitlab.gnome.org/GNOME/pitivi/-/milestones/9#tab-issues

**Comment by aleb** [comment]
If the TCROSS cursor icon is missing then it means it's missing from your system. Make sure it's available on your system.

**Comment by hfiguiere** [comment]
never had that issue. 22.06 is available. Let us know if this is still a problem with that new version.

**Comment by snydox** [comment]
It's working fine now. Thanks!

**Comment by hfiguiere** [comment]
closed with #33
